# Generated by Django 3.0.4 on 2020-03-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32)),
                ('dep', models.CharField(blank=True, max_length=32)),
                ('telphone', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '模板',
            },
        ),
    ]
