# Generated by Django 3.0.4 on 2020-03-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnswerTemplatesManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answertemplate',
            options={'verbose_name': '回答模板'},
        ),
        migrations.RenameField(
            model_name='answertemplate',
            old_name='dep',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='answertemplate',
            old_name='name',
            new_name='child_title',
        ),
        migrations.RemoveField(
            model_name='answertemplate',
            name='telphone',
        ),
        migrations.AddField(
            model_name='answertemplate',
            name='child_type',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='answertemplate',
            name='title',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='answertemplate',
            name='type',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
