# Generated by Django 3.0.4 on 2020-03-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnswerTemplatesManager', '0002_auto_20200307_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='answertemplate',
            name='content',
            field=models.CharField(blank=True, max_length=32, verbose_name='内容'),
        ),
        migrations.AddField(
            model_name='answertemplate',
            name='create_time',
            field=models.CharField(blank=True, max_length=32, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='answertemplate',
            name='author',
            field=models.CharField(blank=True, max_length=32, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='answertemplate',
            name='child_title',
            field=models.CharField(blank=True, max_length=32, verbose_name='子标题'),
        ),
        migrations.AlterField(
            model_name='answertemplate',
            name='child_type',
            field=models.CharField(blank=True, max_length=32, verbose_name='子类别'),
        ),
        migrations.AlterField(
            model_name='answertemplate',
            name='title',
            field=models.CharField(blank=True, max_length=32, verbose_name='主标题'),
        ),
        migrations.AlterField(
            model_name='answertemplate',
            name='type',
            field=models.CharField(blank=True, max_length=32, verbose_name='主类别'),
        ),
    ]
