# Generated by Django 2.2.5 on 2020-04-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnswerTemplatesManager', '0007_auto_20200313_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='answertemplate',
            name='is_passed',
            field=models.BooleanField(blank=True, default=True, max_length=32, verbose_name='创建时间'),
        ),
    ]
