# Generated by Django 2.2.5 on 2020-04-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnswerTemplatesManager', '0008_answertemplate_is_passed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answertemplate',
            name='is_passed',
            field=models.BooleanField(default=True, verbose_name='是否审核通过'),
        ),
    ]
