# Generated by Django 2.2.5 on 2020-04-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnswerTemplatesManager', '0010_auto_20200406_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answertemplate',
            name='is_passed',
            field=models.BooleanField(default=False, verbose_name='是否审核通过'),
        ),
    ]
