# Generated by Django 2.2.5 on 2020-04-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnswerTemplatesManager', '0011_auto_20200406_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answertemplate',
            name='is_passed',
        ),
        migrations.AlterField(
            model_name='answertemplate',
            name='type',
            field=models.IntegerField(default=4, max_length=32, verbose_name='主类别'),
        ),
    ]
