# Generated by Django 2.2.5 on 2020-04-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnswerTemplatesManager', '0012_auto_20200406_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answertemplate',
            name='type',
            field=models.CharField(max_length=32, verbose_name='主类别'),
        ),
    ]
