# Generated by Django 2.2.5 on 2020-04-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnswerTemplatesManager', '0013_auto_20200406_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='answertemplate',
            name='is_passed',
            field=models.BooleanField(default=False, verbose_name='是否审核通过'),
        ),
        migrations.AlterField(
            model_name='answertemplate',
            name='type',
            field=models.IntegerField(choices=[(1, '外盘'), (2, '保险'), (3, '税务'), (4, '股票')], default=4, verbose_name='主类别'),
        ),
    ]
