# Generated by Django 2.2.5 on 2020-04-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnswerTemplatesManager', '0014_auto_20200406_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answertemplate',
            name='create_time',
            field=models.CharField(blank=True, max_length=32, verbose_name='最后更新时间'),
        ),
    ]
