# Generated by Django 2.2.5 on 2020-04-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnswerTemplatesManager', '0015_auto_20200407_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answertemplate',
            name='type',
            field=models.CharField(default=4, max_length=32, verbose_name='主类别'),
        ),
    ]
