# Generated by Django 2.2.5 on 2020-04-09 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnswerTemplatesManager', '0018_auto_20200408_1620'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
