# Generated by Django 2.2.5 on 2020-04-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LocalDicManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptstringdicstring',
            name='concept_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='概念名称'),
        ),
    ]
